#!perl 
use warnings;
use strict;

use Test::More;

{
    ## no critic

    eval " 
        use Test::Perl::Critic (-exclude => [
                            'ProhibitNoStrict',
                            'RequireBarewordIncludes',
                            'ProhibitNestedSubs',
                        ]);
    ";
};

plan skip_all => "Test::Perl::Critic not installed" if $@;


all_critic_ok('.');

